### ISSUE TITLE
Suggestion: Add documentation around requiring a GameObject named SignInCanvas

### ISSUE THREAD

**Issue by nitrixion** [peterhorsley/Unity3D.Authentication.Example#1]
First off, thanks for this example implementation.  It has been extremely helpful in getting up and running with OAuth through IdentityServer in Unity.

Currently, the Unity Implementation expects a GameObject named "SignInCanvas" to have a script with an "OnAuthReply(string)" method to receive the response from the platform specific web view.  I have not found this documented anywhere in this repo.

My suggestion is to add a line to the README documenting this.  Additionally, a config option to change this name would be useful.

Thanks again for this extremely useful example!

**Comment by styk-tv** [comment]
@nitrixion hi, can I quickly ask, did you make it work in 2018.2? it seems i'm missing a step, i can't get the browser to show up on android nor ios.

**Comment by nitrixion** [comment]
> @nitrixion hi, can I quickly ask, did you make it work in 2018.2? it seems i'm missing a step, i can't get the browser to show up on android nor ios.

Hey!  Yes, I'm currently using the code in this repo as a reference for an app in Unity 2018.2.12f1 on Android.  Note: It will not work in editor or on emulator, at least I didn't have much luck getting it to work there.

On android, if you export the project then debug through Android Studio, is there anything interesting in logcat or debug output?

**Comment by peterhorsley** [comment]
@nitrixion Sure i'll update the README as suggested
@styk-tv Yes logcat output will be a good start, as well as other info such as android version etc.  note i don't think you need to export the project, you can just ensure the 'script debugging' is checked in unity on the build settings for android, and then when you run the app, you should see output in logcat.  also, i assume you are just trying to run this example without any modification.

**Comment by styk-tv** [comment]
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.13.6 x86_64
```
+tried with `Android 26.0.2 - 27.0.3 - 28.0.2` on Emulators 26 and 28
+`java 1.8.0_51-b16`

@nitrixion thanks for the real device suggestion, yes no handling for editor but spent most of my time on iOS and Android emulators but could not get browser to show up. Tried several 2018.2.* versions last one was 10f1

@peterhorsley will try logcat but unfortunately could not get a single build to pop a browser on many different macs, maybe i'm missing a step on all of them, unlikely. i was about try downgrading to exact version you used to confirm. but now i will try real device first and report.

**Comment by peterhorsley** [comment]
documentation added to readme for gameobject named signincanvas, closing this issue as per original report.
