### ISSUE TITLE
Re-compile IdentityModel Protection Level

### ISSUE THREAD

**Issue by cubin03** [peterhorsley/Unity3D.Authentication.Example#2]
Following the steps provided:
"Unity does not support nuget nicely, so you must clone and compile IdentityModel.OidcClient2 solution using Visual Studio 2017.
Copy the release binaries from IdentityModel.OidcClient/bin/release/net452 to a folder in your Unity project's Assets folder.
Delete System.Runtime.InteropServices.RuntimeInformation.dll as this DLL is not compatible with Unity."

I needed to change the "code id_token" strings to "code" and attempted a recompile. Dragging in the new binaries to Unity I have compile error for LogSerializer

"Assets/UnityAuthClient.cs(23,13): error CS0122: `IdentityModel.OidcClient.Infrastructure.LogSerializer' is inaccessible due to its protection level"

Please advise

**Comment by peterhorsley** [comment]
@cubin03 that error will appear if you are not compiling the latest IdentityModel.OidcClient2 repo as there was a code change that went into that repo not too long ago relating to the LogSerializer.  I just cloned and it built successfully in VS2017, and copied the binaries to Unity and do not get this error.  

Not sure what your change to "code id_token" is doing or how it is related.

**Comment by cubin03** [comment]
I was able to resolve my issue a while back. Thank you for response though. You can close this issue.
